name: Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use secret
        run: |
          echo "连接地址是: ${{ secrets.DEV_TAPDATA_ACCESS_CODE }}"
